---
version: "3"
services:
  mongo:
    image: mongo

  prometheus:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile-prometheus
    ports:
      - "9090:9090"

  proxy:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
    environment:
      - ENVOY_CLUSTER=proxy
      - ENVOY_CONFIG=/etc/envoy/proxy-xds.yaml
    ports:
      - "80:10000"   # map envoy ingress
      - "9901:9901"  # map envoy admin

  users-v2:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
    command: ["users-v2", "-w", "0.0.0.0:11000"]  # use envoy egress
    environment:
      - ENVOY_CONFIG=/etc/envoy/sidecar-xds.yaml

  widgets-v2:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
    command: ["widgets-v2", "-m", "0.0.0.0:27017"]  # use envoy mongo proxy
    environment:
      - ENVOY_CONFIG=/etc/envoy/sidecar-mongo.yaml

  xds:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
    command: ["xds-docker"]
    environment:
      - ENVOY_CONFIG=/etc/envoy/sidecar.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
