---
descriptors:
  - key: authenticated
    rate_limit:
      requests_per_unit: 1
      unit: minute
    value: "false"

  - key: remote_address
    rate_limit:
      requests_per_unit: 25
      unit: second

domain: gateway
