domain: gateway
descriptors:
  - key: authenticated
    rate_limit:
      requests_per_unit: 1
      unit: minute
    value: "false"

  - key: remote_address
    rate_limit:
      unit: minute
      requests_per_unit: 60
